apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-app
  labels:
    app: cockroachdb-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cockroachdb-app
  template:
    metadata:
      labels:
        app: cockroachdb-app
    spec:
      containers:
        - name: cockroachdb-app
          image: "martijnstraatman/cockroachdb-app:latest"
          env:
          - name: CLUSTER_NAME
            value: "os-test"
          volumeMounts:
            - name: cacerts
              mountPath: "/certs"
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      volumes:
        - name: cacerts
          secret:
            secretName: cacerts
            defaultMode: 0600
---
kind: Service
apiVersion: v1
metadata:
  name: cockroachdb-app
  namespace: os-test
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: cockroachdb-app
