---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cockroachdb-app
      labels:
        app: cockroachdb-app
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: cockroachdb-app
      template:
        metadata:
          labels:
            app: cockroachdb-app
        spec:
          containers:
            - name: cockroachdb-app
              image: "martijnstraatman/cockroachdb-app:latest"
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /health
                  port: http
              readinessProbe:
                httpGet:
                  path: /health
                  port: http
              imagePullPolicy: Always

        ---
          apiVersion: v1
          kind: Service
          metadata:
            name: cockroachdb-app
            labels:
              app: cockroachdb-app
          spec:
            ports:
              - port: 80
                targetPort: http
                protocol: TCP
                name: http
            selector:
              app: cockroachdb-app
